version: '3.8'
services:
  sqlserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrong!Passw0rd
      MSSQL_PID: Developer
    ports:
      - 1433:1433
    volumes:
      - d:\_docker\mssql\data:/var/opt/mssql/data
      - d:\_docker\mssql\log:/var/opt/mssql/log
      - d:\_docker\mssql\backup:/var/opt/mssql/backup
      - d:\_docker\mssql\secrets:/var/opt/mssql/secrets